### ISSUE TITLE
Npm Publishing

### ISSUE THREAD

**Issue by serdarde** [PaoloMessina/OpenUrlExt#4]
Hi, thanks for the plugin, it is the only plugin works for IOS properly.

But there was a problem with adobe phonegap build system. Therefore I added it in to npm publish list.

Please accept my commits and change your paket name from it.almaviva.openurlext to "cordova-plugin-openurlext"

Thank you

**Comment by PaoloMessina** [comment]
Hi serdarde,
thanks for your contribution, i already merge your pull request and change to "cordova-plugin-openurlext".
